In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset = pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
# dataset.column will display the list of colouns of datasets
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [8]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [9]:
dependent=dataset[['charges']]

In [10]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [11]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(independent, dependent, test_size=0.30, random_state=0 )

In [12]:
# Since below SVR model prediction is low we are using standardScaler, the fit_transform will calculat X-Mean/Standard deviation
#for x_train data for x_test date only transform is used as same mean and standard deviation in previous step will be used
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
# below we only use transfor as the mean and standard diviation will be used from previous step
x_test=sc.transform(x_test)

In [115]:
from sklearn.svm import SVR
# since pre processing and blow rbs not have required prediction will try different option like poly, sigmoid
#regressor = SVR(kernel="linear",C=10)
#regressor = SVR(kernel="linear",C=1000)
#regressor = SVR(kernel="linear",C=2000)
#regressor = SVR(kernel="linear",C=3000)

#regressor = SVR(kernel="rbf",C=10)
#regressor = SVR(kernel="rbf",C=1000)
#regressor = SVR(kernel="rbf",C=2000)
#regressor = SVR(kernel="rbf",C=3000)

#regressor = SVR(kernel="poly",C=10)
#regressor = SVR(kernel="poly",C=1000)
#regressor = SVR(kernel="poly",C=2000)
#regressor = SVR(kernel="poly",C=3000)

#regressor = SVR(kernel="sigmoid",C=10)
#regressor = SVR(kernel="sigmoid",C=1000)
#regressor = SVR(kernel="sigmoid",C=2000)
#regressor = SVR(kernel="sigmoid",C=3000)

#regressor = SVR(kernel="precomputed",C=10)
#regressor = SVR(kernel="sigmoid",C=1000)
#regressor = SVR(kernel="sigmoid",C=2000)
#regressor = SVR(kernel="sigmoid",C=3000)



regressor.fit(x_train,y_train)

C:\Users\I308878\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

ValueError: Precomputed matrix must be a square matrix. Input is a 936x5 matrix.

In [ ]:
# this shod how many data point it plotted
regressor.n_support_

In [ ]:
# list the support vector or data points
regressor.support_

In [ ]:
# regressor.predict is the functiom used to predict the output based on the x_test data and y_test is the actual data
#use to cross check the prediction
y_pred = regressor.predict(x_test)

In [ ]:
# sklearn.metric is library and r2.score is function used to create the metrics which will calculate the accuracy of the prediction 
# with the y_test which is actual test data and y_pred is the predicted data
from sklearn.metrics import r2_score
r_score = r2_score(y_test,y_pred)

In [ ]:
r_score